### ISSUE TITLE
Feature(UI): Add Logo

### ISSUE THREAD

**Issue by theNaut1lus** [TestDotCom/Allun.ga#1]
Hey, love this new repo, would love to do my part in contributing on this.

I just checked out the website and I have found that you have a logo linked in the readme and in the `<title>` of the page but not inside the actual website.
It would be an amazing UI addition if we added the logo somewhere, would love to discuss with you on this, hopefully you consider this issue.

**Comment by testdotcom** [comment]
@co16353sidak Yep you're right, I've made that logo today and I don't know where to place it, maybe centered on the top? Well if you have suggestions feel free to go on :)

**Comment by theNaut1lus** [comment]
If we place it on the top it kind of pushes the main working area (input fields for urls etc) further down, instead we could either add it on the left alongside the navbar or add it on the bottom right corner

**Comment by testdotcom** [comment]
I'll try to inline it on the left with the TopBar, on the bottom it won't be noticed by phone users

**Comment by theNaut1lus** [comment]
@TestDotCom I would like to work on this, why don't I have a go and send a PR for this ?

**Comment by testdotcom** [comment]
Sure go on :+1:
